version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    ports:
      - "9090:9090"
    volumes:
      - .:/var/www
    networks:
      - app_network
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: laravel_db
    environment:
      MYSQL_ROOT_PASSWORD: "your_root_password_here"  # Password root MySQL
      MYSQL_DATABASE: ${DB_DATABASE}  # Nama database yang akan dibuat
      MYSQL_USER: ${DB_USERNAME}  # Nama pengguna untuk database
      MYSQL_PASSWORD: ${DB_PASSWORD}  # Password untuk pengguna database
    volumes:
      - laravel_db_data:/var/lib/mysql  # Menyimpan data MySQL
    ports:
      - "3306:3306"  # Port MySQL
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  mysql_data:
    driver: local
