version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    ports:
      - "9090:9090"
    volumes:
      - .:/var/www
    networks:
      - app_network
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: laravel_db
    environment:
      DB_PASSWORD: 3#Enjbh^cbbJ#m@f
      DB_DATABASEE: pend_w1suda
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  mysql_data:
    driver: local
